
server:
    port: 8084
spring:
    application:
        name: gateway-demo
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://192.168.50.150:8081/eureka/,http://192.168.50.150:8082/eureka

zuul:
    routes:
        mybatis-demo:
            paths: mybatis-demo/*
            url: http://192.168.50.150:8083